server:
 servlet:
  context-path: /flink

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 111111
    url: jdbc:mysql://localhost:3306/flink
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /
      suffix: .jsp
    date-format: yyyy-MM-dd
mybatis:
  type-aliases-package: com.bing.entity
  mapper-locations: com/bing/mapper/*Mapper.xml
